CREATE DATABASE "AuditLogsMS";
CREATE DATABASE "KardexMS";
CREATE DATABASE "MailsMS";
CREATE DATABASE "MessagesMS";
CREATE DATABASE "PaymentsMS";
CREATE DATABASE "ProductsMS";
CREATE DATABASE "ShipmentsMS";
CREATE DATABASE "ShopingsMS";
CREATE DATABASE "UsersManagerMS";










