server {
    listen 80;
    server_name localhost;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/auth   { proxy_pass http://users-manager:5001; }
    location /api/users  { proxy_pass http://users-manager:5001; }

    location /api/categories  { proxy_pass http://products:5002; }
    location /api/subcategories { proxy_pass http://products:5002; }
    location /api/references  { proxy_pass http://products:5002; }
    location /api/products    { proxy_pass http://products:5002; }
    location /api/stocks      { proxy_pass http://products:5002; }

    location /api/carts        { proxy_pass http://shopings:5003; }
    location /api/cart-details { proxy_pass http://shopings:5003; }
    location /api/orders       { proxy_pass http://shopings:5003; }

    location /api/payments  { proxy_pass http://payments:5004; }

    location /api/shipments { proxy_pass http://shipments:5005; }

    location /api/kardex { proxy_pass http://kardex:5006; }

    location /api/audit-logs { proxy_pass http://audit-logs:5007; }

    location /api/mails { proxy_pass http://mails:5008; }

    location /api/messages { proxy_pass http://messages:5009; }

    location /api-docs { proxy_pass http://users-manager:5001; }
}
